App-Estudio-Juridico-Kinexo/App-Estudio-Juridico-Kinexo/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App_Estudio_Juridico_Kinexo.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }
    }
}

App-Estudio-Juridico-Kinexo/App-Estudio-Juridico-Kinexo/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App_Estudio_Juridico_Kinexo.Models;
using App_Estudio_Juridico_Kinexo.Contracts;

namespace App_Estudio_Juridico_Kinexo.Controllers
{
    public class NewsController : Controller
    {
        private INews _news;
        public NewsController(INews News)
        {
            _news = News;
        }
        
        // GET: News
        public ActionResult Index()
        {
            return View(_news.GetNews());
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: News/Create
        [HttpPost]
        public ActionResult Create(NewsModel model)
        {
            model.PublicationDate = DateTime.Today;
            model.NewID = _news.GetNextNewID();
            if (ModelState.IsValid)
            {
                if (_news.Create(model))
                {
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_news.GetNewByID(id));
        }

        [Authorize(Roles = "Admin")]
        // POST: News/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, NewsModel model)
        {
            if (ModelState.IsValid)
            {
                if (_news.Edit(id, model))
                {
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        // GET: News/Delete/5
        public ActionResult Delete(int id)
        {
            if (_news.Delete(id))
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: News/Delete/5
        [HttpPost]
        public string Delete(int id, NewsModel model)
        {
            return "Se eliminó la noticia nro. " + id.ToString();
        }
    }
}

App-Estudio-Juridico-Kinexo/App-Estudio-Juridico-Kinexo/Views/Shared/EmployeesIndex.cshtml
@{
    ViewBag.Title = "Empleados";
}

App-Estudio-Juridico-Kinexo/App-Estudio-Juridico-Kinexo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Estudio Juridico "K.U. y Asociados"</title>
    <link href="https://fonts.googleapis.com/css?family=Abhaya+Libre" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/_layout.css")
    <link href="~/Content/Shared/loginpartial.css" rel="stylesheet" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/Home/index.css" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom CSS -->

    <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/css/one-page-wonder.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div class="container">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color: burlywood">
            <div class="container containerDiv">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("E.J. 'K. U. y Asociados'", "Index", "Home", new { area = "" }, new { @class = "navbar-brand barraNav" })
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Incio", "Index", "Home","", new { @class = "barraNav" })</li>
                        <li>@Html.ActionLink("¿Quiénes somos?", "About", "Home", "", new { @class = "barraNav" })</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home", "", new { @class = "barraNav" })</li>
                        <li>@Html.ActionLink("Noticias", "Index", "News", "", new { @class = "barraNav" })</li>
                        @if (User.IsInRole("Client"))
                        {
                            <li>@Html.ActionLink("Mis Casos", "MyCases", "Clients", "", new { @class = "barraNav" })</li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Nuevo Empleado", "Index", "Employee", "", new { @class = "barraNav" })</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
        <div class="">
            @RenderBody()
            <footer class="pull-right">
                <p class="barraNav">&copy; @DateTime.Now.Year - Estudio Juridico "K.U. y Asociados"</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        <script src="~/Scripts/Procedures/create.js"></script>
        <script src="~/Scripts/Procedures/edit.js"></script>
        @RenderSection("scripts", required: false)

    </div>
</body>
</html>